services:
  ad-client:
    container_name: ad-client
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - delegation_network

  kerby-client:
    container_name: kerby-client
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - delegation_network
    volumes:
      - ./kerby-krb5.conf:/etc/krb5.conf

networks:
  delegation_network:
    driver: bridge