services:
  ad-client:
    container_name: ad-client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - delegation_network

  mit:
    container_name: mit
    build:
      context: ./kdc/mit
      dockerfile: ./Dockerfile
#      args:
#        APT_MIRROR: "ftp.uni-stuttgart.de"
    ports:
      - "8088:8088/tcp"
      - "8088:8088/udp"
      - "8750:8750/tcp"
    networks:
      - delegation_network
    volumes:
      - ./kdc/mit/keytabs:/etc/keytabs

  mit-client:
    container_name: mit-client
    build:
      context: ./client
      dockerfile: Dockerfile
    extra_hosts:
      - "frontend.iam.dev:host-gateway"
      - "prefrontend.iam.dev:host-gateway"
    networks:
      - delegation_network
    volumes:
      - ./client/mit-krb5.conf:/etc/krb5.conf
      - ./kdc/mit/keytabs:/etc/keytabs

  kerby:
    container_name: kerby
    build:
      context: ./kdc/kerby
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888/udp"
      - "8888:8888/tcp"
    volumes:
      - ./kdc/kerby/conf:/opt/kerby/kdc-dist/conf
      - ./kdc/kerby/keytabs:/opt/kerby/kdc-dist/keytabs
    networks:
      - delegation_network

  kerby-client:
    container_name: kerby-client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - delegation_network
    volumes:
      - ./client/kerby-krb5.conf:/etc/krb5.conf

networks:
  delegation_network:
    driver: bridge
    